"""Extract this client's reflected EStat names; validates PE mapping and every entry."""
import argparse
import json
import pathlib
import struct


def extract(path):
    with path.open('rb') as source:
        source.seek(0x3C)
        pe = struct.unpack('<I', source.read(4))[0]
        source.seek(pe)
        if source.read(4) != b'PE\0\0':
            raise ValueError('Expected PE image')
        machine, sections, _, _, _, optional_size, _ = struct.unpack('<HHIIIHH', source.read(20))
        optional = source.read(optional_size)
        if machine != 0x8664 or struct.unpack_from('<H', optional)[0] != 0x20B:
            raise ValueError('Expected x64 PE32+')
        base = struct.unpack_from('<Q', optional, 24)[0]
        mappings = []
        for _ in range(sections):
            section = source.read(40)
            _, rva, raw_size, raw = struct.unpack_from('<IIII', section, 8)
            mappings.append((rva, raw_size, raw))

        def read(rva, size):
            for start, length, raw in mappings:
                if start <= rva and rva + size <= start + length:
                    source.seek(raw + rva - start)
                    value = source.read(size)
                    if len(value) == size:
                        return value
            raise ValueError(f'Unmapped or truncated RVA {rva:#x}')

        rows = []
        for value in range(603):
            rva = 0xDD58940 + value * 16
            pointer, enum_value = struct.unpack('<QQ', read(rva, 16))
            name = read(pointer - base, 160).split(b'\0', 1)[0].decode('ascii')
            if enum_value != value or not name.startswith('EStat::'):
                raise ValueError(f'Enum table mismatch at {rva:#x}; wrong client version')
            rows.append({'rva': hex(rva), 'name': name, 'value': value})
        if rows[193]['name'] != 'EStat::HPMax' or rows[-1]['name'] != 'EStat::Max':
            raise ValueError('Known anchors do not match')
        return rows


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('dump', type=pathlib.Path)
    parser.add_argument('header', type=pathlib.Path)
    parser.add_argument('evidence', type=pathlib.Path)
    args = parser.parse_args()
    rows = extract(args.dump)
    lines = ['#pragma once', '#include <array>', 'namespace aion {',
             '// 2026-09-24 client, reflected EStat table RVA 0xDD58940.',
             '// Generated by scripts/extract_stat_enum.py. Names do not establish value scaling.',
             'inline constexpr std::array<const char*, 602> statNames = {']
    lines += ['    ' + json.dumps(row['name'][7:]) + ', // ' + str(row['value']) for row in rows[:-1]]
    lines += ['};', '}']
    args.header.write_text('\n'.join(lines) + '\n', encoding='utf8')
    args.evidence.write_text(json.dumps(rows, indent=2), encoding='utf8')
    print(f'Validated {len(rows)} reflected enum entries; generated {len(rows)-1} names.')
